version: '3'

services:
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile.prod
    container_name: udemy-docker-front
    command: serve -s build -l 3000
#    ports:
#      - "3000:3000"
    restart: unless-stopped
    networks:
      - udemy-docker-network

  api:
    build: ./api
    container_name: udemy-docker-api
    command: yarn start
    restart: unless-stopped
#    ports:
#      - "3001:3001"
    environment:
      - API_PORT=3001
      - MONGO_URL=mongodb://api_db:27017/api
      - AUTH_API_URL=http://auth:3002/api
    depends_on:
      - api_db
    networks:
      - udemy-docker-network

  auth:
    build: ./auth
    container_name: udemy-docker-auth
    command: yarn start
    restart: unless-stopped
#    ports:
#      - "3002:3002"
    environment:
      - AUTH_PORT=3002
    depends_on:
      - auth_db
    networks:
      - udemy-docker-network


  api_db:
    image: mongo:latest
    container_name: udemy-docker-api-db
    volumes:
    - mongodb_api:/data/db
    networks:
      - udemy-docker-network


  auth_db:
    image: mongo:latest
    container_name: udemy-docker-auth-db
    volumes:
    - mongodb_auth:/data/db
    networks:
      - udemy-docker-network


  nginx:
    image: nginx:stable-alpine
    container_name: udemy-docker-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - frontend
      - api
      - auth
    networks:
      - udemy-docker-network

volumes:
  mongodb_api:
  mongodb_auth:

networks:
  udemy-docker-network:
    driver: bridge
